# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7279d4ac663b49d35a717b53887779c0554e5460595ad387c197a671a4d0f2e9279747cf0763eadaff62729113c3c1cfd9730a97e23df51b85884a3bea93db90

test:
  secret_key_base: 3e692ab64ed44af304ee01cf9a64364978542a59ec11a247fadee86cbf62db28a0e63556aebe009eeee9b9643e3dd4eb53b1062944e9382611d52158b659e8fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
